displays:
-   id: 1
    name: Left
    driver:
        type: paged
        pages:
            -   type: ping_packet_loss
            -   type: ping_rtt
-   id: 2
    name: Right
    driver:
        type: paged
        pages:
            -   type: dummy
