displays:
-   id: 1
    name: Left
    driver:
        type: paged
        pages:
            -   type: ping
        transition:
            type: none
-   id: 2
    name: Right
    driver:
        type: paged
        pages:
            -   type: ntp
        transition:
            type: none
