displays:
-   id: 1
    name: Left
    driver:
        type: paged
        pages:
            -   type: lte
            -   type: ping
-   id: 2
    name: Right
    driver:
        type: paged
        pages:
            -   type: ntp
            -   type: upspower
